// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Account
    {
        public Account()
        {
            Bills = new HashSet<Bill>();
            Tickeds = new HashSet<Ticked>();
        }

        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime Date { get; set; }
        public bool? Gender { get; set; }
        public string Address { get; set; }
        public int? CinemaId { get; set; }
        public bool? IsLogged { get; set; }
        public int? RoleId { get; set; }
        public bool? Active { get; set; }
        public string Avatar { get; set; }

        public virtual Cinema Cinema { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<Ticked> Tickeds { get; set; }
    }
}