// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Bill
    {
        public Bill()
        {
            ServiceInBills = new HashSet<ServiceInBill>();
            Tickeds = new HashSet<Ticked>();
        }

        public int Id { get; set; }
        public int? AccountId { get; set; }
        public int? SchedulingId { get; set; }
        public int? PaymentId { get; set; }
        public string CouponId { get; set; }
        public DateTime? Time { get; set; }
        public int? Total { get; set; }

        public virtual Account Account { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual ICollection<ServiceInBill> ServiceInBills { get; set; }
        public virtual ICollection<Ticked> Tickeds { get; set; }
    }
}