// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Cinema
    {
        public Cinema()
        {
            Accounts = new HashSet<Account>();
            FilmInCinemas = new HashSet<FilmInCinema>();
            Rooms = new HashSet<Room>();
            Schedulings = new HashSet<Scheduling>();
            ServiceInCinemas = new HashSet<ServiceInCinema>();
        }

        public int Id { get; set; }
        public string Address { get; set; }
        public int? LocationId { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }
        public string Name { get; set; }

        public virtual Location Location { get; set; }
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<FilmInCinema> FilmInCinemas { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Scheduling> Schedulings { get; set; }
        public virtual ICollection<ServiceInCinema> ServiceInCinemas { get; set; }
    }
}