// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Coupon
    {
        public Coupon()
        {
            Bills = new HashSet<Bill>();
        }

        public string Id { get; set; }
        public int? Discount { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public int? PriceRange { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<Bill> Bills { get; set; }
    }
}