// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class FilmInCinema
    {
        public FilmInCinema()
        {
            Schedulings = new HashSet<Scheduling>();
        }

        public int FilmId { get; set; }
        public int CinemaId { get; set; }
        public DateTime? Startime { get; set; }
        public DateTime? Endtime { get; set; }

        public virtual Cinema Cinema { get; set; }
        public virtual Film Film { get; set; }
        public virtual ICollection<Scheduling> Schedulings { get; set; }
    }
}