// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Film
    {
        public Film()
        {
            FilmInCinemas = new HashSet<FilmInCinema>();
            TypeInFilms = new HashSet<TypeInFilm>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public string Actor { get; set; }
        public int? Time { get; set; }
        public string Language { get; set; }
        public int? Rated { get; set; }
        public string Trailer { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<FilmInCinema> FilmInCinemas { get; set; }
        public virtual ICollection<TypeInFilm> TypeInFilms { get; set; }
    }
}