// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Location
    {
        public Location()
        {
            Cinemas = new HashSet<Cinema>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Cinema> Cinemas { get; set; }
    }
}