// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Room
    {
        public Room()
        {
            Schedulings = new HashSet<Scheduling>();
            Seats = new HashSet<Seat>();
        }

        public int Id { get; set; }
        public int? CinemaId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual Cinema Cinema { get; set; }
        public virtual ICollection<Scheduling> Schedulings { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}