// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class RoomDTO
    {
        

        public int Id { get; set; }
        public string Cinema { get; set; }
        public int? CinemaId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

      
    }
}