// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Seat
    {
        public Seat()
        {
            Tickeds = new HashSet<Ticked>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public int? RoomId { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual Room Room { get; set; }
        public virtual ICollection<Ticked> Tickeds { get; set; }
    }
}