// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class ServiceInCinema
    {
        public ServiceInCinema()
        {
            ServiceInBills = new HashSet<ServiceInBill>();
        }

        public int Id { get; set; }
        public int CinemaId { get; set; }
        public int ServiceId { get; set; }
        public int? Quantity { get; set; }
        public bool? Active { get; set; }

        public virtual Cinema Cinema { get; set; }
        public virtual Service Service { get; set; }
        public virtual ICollection<ServiceInBill> ServiceInBills { get; set; }
    }
}