// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Service
    {
        public Service()
        {
            ServiceInCinemas = new HashSet<ServiceInCinema>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public int? Price { get; set; }
        public int? Quantity { get; set; }
        public string Description { get; set; }
        public bool? Active { get; set; }

        public virtual ICollection<ServiceInCinema> ServiceInCinemas { get; set; }
    }
}