// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class Ticked
    {
        public int SeatId { get; set; }
        public int BillId { get; set; }
        public int SchedulingId { get; set; }
        public int AccountId { get; set; }
        public decimal? Price { get; set; }
        public bool? Checking { get; set; }

        public virtual Account Account { get; set; }
        public virtual Bill Bill { get; set; }
        public virtual Seat Seat { get; set; }
    }
}