// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BusinessObject.Models
{
    public partial class TypeInFilm
    {
        public int TypeId { get; set; }
        public int FilmId { get; set; }
        public bool? Active { get; set; }

        public virtual Film Film { get; set; }
        public virtual Types Type { get; set; }
    }
}